services:
  keystone-db:
    image: postgres:18
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: 'keystone'
      POSTGRES_USER: 'keystone'
      POSTGRES_PASSWORD: 'test123'
    networks:
      - keystone_network
    ports:
      - "5432:5432"

  keystone-redis:
    image: redis:8.2
    volumes:
      - redis_data:/data
    networks:
      - keystone_network
    ports:
      - '6379:6379'

  keystone-rabbitmq:
    image: rabbitmq:4.2-management
    environment:
      RABBITMQ_DEFAULT_USER: keystone
      RABBITMQ_DEFAULT_PASS: test123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - keystone_network
    ports:
      - '15672:15672'
      - '5672:5672'
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keystone-maildev:
    image: maildev/maildev
    hostname: maildev
    networks:
      - keystone_network
    ports:
      - '1080:1080'
      - '1025:1025'

  keystone-nginx:
    image: nginx:1.29.3
    ports:
      - '8000:80'
    volumes:
      - './backend:/var/www/html'
      - './backend/.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - keystone-app
    networks:
      - keystone_network

  keystone-app:
    build:
      context: 'backend'
      dockerfile: '.docker/Dockerfile'
    depends_on:
      - keystone-db
      - keystone-redis
      - keystone-rabbitmq
    volumes:
      - ./backend:/var/www/html
    networks:
      - keystone_network


  keystone-frontend:
    build:
      context: 'frontend'
      dockerfile: '.docker/Dockerfile'
    volumes:
      - ./frontend:/app
    environment:
      CI: true
      CHOKIDAR_USEPOLLING: true
    ports:
      - "3000:3000"
      - "3001:3001"

  keystone-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
    environment:
      - cluster.name=keystone-es-cluster
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=test321
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - keystone_network
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "keystone_data:/usr/share/elasticsearch/data"
    ports:
      - '9200:9200'

volumes:
  db_data:
  redis_data:
  rabbitmq_data:
  keystone_data:

networks:
  keystone_network:
    driver: bridge